version: '3.1'
services:
  db:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: pet_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../mysql_pet_db_data:/var/lib/mysql